version: '3.8'

services:
  # 数据库服务
  my-oj-db:
    image: mysql:8
    container_name: my-oj-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=MYSQL_PASSWORD_PLACEHOLDER
      - MYSQL_DATABASE=oj_db
    volumes:
      - my-oj-db-data:/var/lib/mysql
      - /home/hjl/my_project/my_oj/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
    networks:
      - my-oj-network

  # 后端服务
  my-oj-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-oj-backend:1.0.0
    container_name: my-oj-backend
    ports:
      - "8101:8101"
    depends_on:
      - my-oj-db
    command:
      - "--codesandbox.url=http://172.25.66.109:8100/executeCode"
      - "--codesandbox.type=remote"
    networks:
      - my-oj-network

networks:
  my-oj-network:
    driver: bridge

volumes:
  my-oj-db-data: